---
kind: pipeline
type: kubernetes
name: prod-deploy-roma-web

trigger:
  event:
    - tag

steps:
  - name: build docker image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.ali
      context: .
      repo: registry.cn-hongkong.aliyuncs.com/binrchq/roma-web
      registry: registry.cn-hongkong.aliyuncs.com
      tags:
        - ${DRONE_TAG}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BUILD_MODE=production
        - NODE_ENV=production
  
  - name: deploy to demo
    image: registry.cn-hongkong.aliyuncs.com/binrcbase/kubectl
    environment:
      KUBECONFIG:
        from_secret: kubeconfig_data
      HOME: /root
      IMAGE_TAG: ${DRONE_TAG}
      NAMESPACE: demo
      DOMAIN: roma-demo.binrc.com
      BACKEND_API_URL: https://roma-demo-api.binrc.com/api/v1
    depends_on:
      - build docker image
    commands:
      - echo "$KUBECONFIG" > /drone/src/kubeconfig
      - |
        sed -e "s|registry.cn-hongkong.aliyuncs.com/binrchq/roma-web:latest|registry.cn-hongkong.aliyuncs.com/binrchq/roma-web:$IMAGE_TAG|g" \
            -e "s|namespace: roma|namespace: $NAMESPACE|g" \
            -e "s|name: roma-web$|name: roma-demo-web|g" \
            -e "s|name: roma-web |name: roma-demo-web |g" \
            -e "s|app: roma-web|app: roma-demo-web|g" \
            -e "s|name: roma-web-service|name: roma-demo-web-service|g" \
            -e "s|name: redirect-to-https|name: demo-redirect-to-https|g" \
            -e "s|name: roma-web-ingress|name: roma-demo-web-ingress|g" \
            -e "s|traefik.ingress.kubernetes.io/router.middlewares: roma-redirect-to-https@kubernetescrd|traefik.ingress.kubernetes.io/router.middlewares: $NAMESPACE-redirect-to-https@kubernetescrd|g" \
            -e "s|- roma.binrc.com|- $DOMAIN|g" \
            -e "s|host: roma.binrc.com|host: $DOMAIN|g" \
            -e "s|name: VITE_ENV|name: VITE_ENV|g" \
            -e "s|value: \"prod\"|value: \"demo\"|g" \
            -e "s|name: VITE_API_BASE_URL|name: VITE_API_BASE_URL|g" \
            -e "s|value: \"https://roma-api.c.binrc.com/api/v1\"|value: \"$BACKEND_API_URL\"|g" \
            deployment/k8s-deployment.yaml > /drone/src/k8s-deployment.demo.yaml
      - |
        # 验证关键配置是否正确替换
        if ! grep -q "value: \"$BACKEND_API_URL\"" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: Failed to replace VITE_API_BASE_URL in demo deployment"
          exit 1
        fi
        if ! grep -q "host: $DOMAIN" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: Failed to replace domain in demo deployment"
          exit 1
        fi
        if ! grep -q "name: roma-demo-web-service" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: Failed to replace service name in demo deployment"
          exit 1
        fi
        if ! grep -q "app: roma-demo-web" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: Failed to replace app label in demo deployment"
          exit 1
        fi
      - kubectl --kubeconfig=/drone/src/kubeconfig apply -f /drone/src/k8s-deployment.demo.yaml
      - kubectl --kubeconfig=/drone/src/kubeconfig rollout status deployment/roma-demo-web -n $NAMESPACE --timeout=3m

  - name: deploy to prod
    image: registry.cn-hongkong.aliyuncs.com/binrcbase/kubectl
    environment:
      KUBECONFIG:
        from_secret: kubeconfig_data
      HOME: /root
      IMAGE_TAG: ${DRONE_TAG}
      NAMESPACE: roma
      DOMAIN: roma.c.binrc.com
      BACKEND_API_URL: https://roma-api.c.binrc.com/api/v1
    depends_on:
      - build docker image
    commands:
      - echo "$KUBECONFIG" > /drone/src/kubeconfig
      - |
        sed -e "s|registry.cn-hongkong.aliyuncs.com/binrchq/roma-web:latest|registry.cn-hongkong.aliyuncs.com/binrchq/roma-web:$IMAGE_TAG|g" \
            -e "s|namespace: roma|namespace: $NAMESPACE|g" \
            -e "s|traefik.ingress.kubernetes.io/router.middlewares: roma-redirect-to-https@kubernetescrd|traefik.ingress.kubernetes.io/router.middlewares: $NAMESPACE-redirect-to-https@kubernetescrd|g" \
            -e "s|- roma.binrc.com|- $DOMAIN|g" \
            -e "s|host: roma.binrc.com|host: $DOMAIN|g" \
            -e "s|name: VITE_ENV|name: VITE_ENV|g" \
            -e "s|value: \"prod\"|value: \"production\"|g" \
            -e "s|name: VITE_API_BASE_URL|name: VITE_API_BASE_URL|g" \
            -e "s|value: \"https://roma-api.c.binrc.com/api/v1\"|value: \"$BACKEND_API_URL\"|g" \
            deployment/k8s-deployment.yaml > /drone/src/k8s-deployment.deploy.yaml
      - |
        # 验证关键配置是否正确替换
        if ! grep -q "value: \"$BACKEND_API_URL\"" /drone/src/k8s-deployment.deploy.yaml; then
          echo "ERROR: VITE_API_BASE_URL not found or incorrect in prod deployment"
          exit 1
        fi
        if ! grep -q "host: $DOMAIN" /drone/src/k8s-deployment.deploy.yaml; then
          echo "ERROR: Failed to replace domain in prod deployment"
          exit 1
        fi
        if ! grep -q "name: roma-web-service" /drone/src/k8s-deployment.deploy.yaml; then
          echo "ERROR: Service name should be roma-web-service in prod deployment"
          exit 1
        fi
        if ! grep -q "app: roma-web" /drone/src/k8s-deployment.deploy.yaml; then
          echo "ERROR: App label should be roma-web in prod deployment"
          exit 1
        fi
      - kubectl --kubeconfig=/drone/src/kubeconfig apply -f /drone/src/k8s-deployment.deploy.yaml
      - kubectl --kubeconfig=/drone/src/kubeconfig rollout status deployment/roma-web -n $NAMESPACE --timeout=3m
