---
kind: pipeline
type: kubernetes
name: prod-deploy-roma-web

trigger:
  event:
    - tag

steps:
  - name: build docker image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.ali
      context: .
      repo: registry.cn-hongkong.aliyuncs.com/binrchq/roma-web
      registry: registry.cn-hongkong.aliyuncs.com
      tags:
        - ${DRONE_TAG}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BUILD_MODE=production
        - NODE_ENV=production
  
  - name: deploy to demo
    image: registry.cn-hongkong.aliyuncs.com/binrcbase/kubectl
    environment:
      KUBECONFIG:
        from_secret: kubeconfig_data
      HOME: /root
      IMAGE_TAG: ${DRONE_TAG}
      NAMESPACE: demo
      DOMAIN: roma-demo.binrc.com
      BACKEND_API_URL: https://roma-demo-api.binrc.com
    depends_on:
      - build docker image
    commands:
      - echo "$KUBECONFIG" > /drone/src/kubeconfig
      - |
        sed -e "s|registry.cn-hongkong.aliyuncs.com/binrchq/roma-web:latest|registry.cn-hongkong.aliyuncs.com/binrchq/roma-web:$IMAGE_TAG|g" \
            -e "s|namespace: roma|namespace: $NAMESPACE|g" \
            -e "s|name: roma-web-service|name: roma-web-service|g" \
            -e "s|name: redirect-to-https|name: redirect-to-https|g" \
            -e "s|name: roma-web-ingress|name: roma-web-ingress|g" \
            -e "s|traefik.ingress.kubernetes.io/router.middlewares: roma-redirect-to-https@kubernetescrd|traefik.ingress.kubernetes.io/router.middlewares: $NAMESPACE-redirect-to-https@kubernetescrd|g" \
            -e "s|- roma.binrc.com|- $DOMAIN|g" \
            -e "s|host: roma.binrc.com|host: $DOMAIN|g" \
            -e "s|value: \"https://roma-api.c.binrc.com\"|value: \"$BACKEND_API_URL\"|g" \
            deployment/k8s-deployment.yaml > /drone/src/k8s-deployment.demo.yaml
      - |
        if ! grep -q "value: \"$BACKEND_API_URL\"" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: Failed to replace VITE_API_BASE_URL in demo deployment"
          exit 1
        fi
      - kubectl --kubeconfig=/drone/src/kubeconfig apply -f /drone/src/k8s-deployment.demo.yaml
      - kubectl --kubeconfig=/drone/src/kubeconfig rollout status deployment/roma-web -n $NAMESPACE --timeout=3m

  - name: deploy to prod
    image: registry.cn-hongkong.aliyuncs.com/binrcbase/kubectl
    environment:
      KUBECONFIG:
        from_secret: kubeconfig_data
      HOME: /root
      IMAGE_TAG: ${DRONE_TAG}
      NAMESPACE: roma
      DOMAIN: roma.c.binrc.com
      BACKEND_API_URL: https://roma-api.c.binrc.com
    depends_on:
      - build docker image
    commands:
      - echo "$KUBECONFIG" > /drone/src/kubeconfig
      - |
        sed -e "s|registry.cn-hongkong.aliyuncs.com/binrchq/roma-web:latest|registry.cn-hongkong.aliyuncs.com/binrchq/roma-web:$IMAGE_TAG|g" \
            -e "s|namespace: roma|namespace: $NAMESPACE|g" \
            -e "s|traefik.ingress.kubernetes.io/router.middlewares: roma-redirect-to-https@kubernetescrd|traefik.ingress.kubernetes.io/router.middlewares: $NAMESPACE-redirect-to-https@kubernetescrd|g" \
            -e "s|- roma.binrc.com|- $DOMAIN|g" \
            -e "s|host: roma.binrc.com|host: $DOMAIN|g" \
            deployment/k8s-deployment.yaml > /drone/src/k8s-deployment.deploy.yaml
      - |
        if ! grep -q "value: \"$BACKEND_API_URL\"" /drone/src/k8s-deployment.deploy.yaml; then
          echo "ERROR: VITE_API_BASE_URL not found or incorrect in prod deployment"
          exit 1
        fi
      - kubectl --kubeconfig=/drone/src/kubeconfig apply -f /drone/src/k8s-deployment.deploy.yaml
      - kubectl --kubeconfig=/drone/src/kubeconfig rollout status deployment/roma-web -n $NAMESPACE --timeout=3m

# secret 来自 Drone 的 Secret 管理，需要先创建 secret 才能使用
---
kind: secret
name: kubeconfig_data
get:
  path: kubeconfig-data
  name: KUBECONFIG_DATA
---
kind: secret
name: docker_username
get:
  path: docker-username
  name: DOCKER_USERNAME
---
kind: secret
name: docker_password
get:
  path: docker-password
  name: DOCKER_PASSWORD
